### ISSUE TITLE
Warning in Chrome

### ISSUE THREAD

**Issue by wamatt** [mahemoff/chrome-boilerplate#1]
Thanks for making this Mike

Noticed something on install:

There were warnings when trying to install this extension:
Permission '_://_.google.com' is unknown or URL pattern is malformed.

![GitHub Logo](http://img.skitch.com/20120729-jbewy3r3pwwqx4aiag7ry85aib.jpg)

**Comment by mahemoff** [comment]
Thanks. Actually I don't think wildcard URL schemes are possible, so I've updated the first \* to http. Good enough for the example.

**Comment by wamatt** [comment]
Cool. Thanks Mike
