### ISSUE TITLE
Unrecognized manifest key 'null'.

### ISSUE THREAD

**Issue by wamatt** [mahemoff/chrome-boilerplate#3]
Warning in Chrome 21

**Comment by Glench** [comment]
that's there purposefully to prevent trailing comma errors in manifest.json, so you can comment/uncomment whatever you'd like and the extension will still load.

**Comment by mahemoff** [comment]
Yeah, it didn't give an error before though, so maybe this little convenience should be removed now?

**Comment by mahemoff** [comment]
Oh, I see @greenido has done it now.
