### ISSUE TITLE
Comment disabling browser_action icon

### ISSUE THREAD

**Issue by Glench** [mahemoff/chrome-boilerplate#9]
Not sure if this is just because I'm running a beta chrome, but the large comment right before "browser_action" in the manifest caused chrome to miss that property and not load the icon. The comment is this one:

  /*****************************************************************************
   DECLARE AT MOST ONE OF THE FOLLOWING UI EXPOSURES
   (A SAMPLE BROWSER ACTION IS PROVIDED BY DEFAULT)
   ****************************************************************************/

Would love to get a confirmation on this on stable chrome.

**Comment by mahemoff** [comment]
Looks like the new parser has a bug in dealing with this. I've updated the comment format now.
